trigger:
- master

pool: Titaniam

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Build
    displayName: Compile and build docker image
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          arguments: '-t helloworld:v1'
          addPipelineData: false
          addBaseImageData: false

- stage: CreateInfra
  displayName: Create Infrastructure
  jobs:
  - job: Terraform
    displayName: TF init and plan
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            cd Deployment/terraform-infra;
            terraform init; terraform plan
