trigger:
- master

pool: Titaniam

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Build
    displayName: Build Maven Project
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
