trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Deployment

pool: Titaniam

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Build
    displayName: Compile and build docker image
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          arguments: '-t helloworld:v1'
          addPipelineData: false
          addBaseImageData: false

- stage: DeployDocker
  displayName: Deploy jar file to virtual machine
  jobs:
  - job: Deployment
    displayName: deploy docker
    steps:
      - task: Bash@3
        displayName: Upload docker file to machine
        inputs:
          targetType: 'inline'
          script: 'docker save -o helloworld.tar helloworld:v1'
      - task: Bash@3
        displayName: Upload file to destination
        inputs:
          targetType: 'inline'
          script: 'ssh ssh adminuser@20.124.218.57 tar czf - helloworld.tar > /tmp/helloworld.tar;'


