trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Deployment
    exclude:
      - ./

pool: Titaniam

variables:
  - group: Azure

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Authentication
    displayName: Authenticate to Azure
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)'