trigger:
- master

pool:
  vmImage: Titaniam

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Build
    displayName: Compile and build docker image
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'